remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Naga Vidya Sirisha Kasi
description: My Portfolio

show_downloads: false
theme: jekyll-theme-minimal
